#!/bin/bash
# =============================================================================
# 3. Deploy Code to EC2
# =============================================================================
# Builds the project, uploads to EC2, and starts as a systemd service.
# Automatically injects S3 credentials from local .env if present.
# Usage: ./3_deploy_code.sh <PUBLIC_IP>
# =============================================================================

set -e

if [ -z "$1" ]; then
    echo "Usage: ./3_deploy_code.sh <PUBLIC_IP>"
    echo ""
    echo "Example: ./3_deploy_code.sh 3.145.67.89"
    exit 1
fi

PUBLIC_IP=$1
KEY_NAME="mcp-server-key"
SSH_KEY="$HOME/.ssh/${KEY_NAME}.pem"
SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

echo ""
echo "=========================================="
echo "  Deploying MCP Server to ${PUBLIC_IP}"
echo "=========================================="
echo ""

# Check SSH key exists
if [ ! -f "$SSH_KEY" ]; then
    echo "❌ SSH key not found: ${SSH_KEY}"
    exit 1
fi

# Navigate to project root
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

echo "Project root: ${PROJECT_ROOT}"
echo ""

# Build project
echo "Building project..."
pnpm build
echo "✓ Build complete"

# Create deployment package
echo ""
echo "Creating deployment package..."
PACKAGE_FILE="/tmp/mcp-server-2.0.tar.gz"
tar -czf "$PACKAGE_FILE" \
    dist/ \
    package.json \
    pnpm-lock.yaml

PACKAGE_SIZE=$(ls -lh "$PACKAGE_FILE" | awk '{print $5}')
echo "✓ Package created: ${PACKAGE_SIZE}"

# Check for local .env with S3 credentials
echo ""
LOCAL_ENV="${PROJECT_ROOT}/.env"
if [ -f "$LOCAL_ENV" ]; then
    echo "✓ Found local .env - will inject S3 credentials automatically"
    # Extract S3-related vars from local .env
    AWS_REGION=$(grep '^AWS_REGION=' "$LOCAL_ENV" | cut -d'=' -f2)
    AWS_BUCKET_NAME=$(grep '^AWS_BUCKET_NAME=' "$LOCAL_ENV" | cut -d'=' -f2)
    AWS_ACCESS_KEY_ID=$(grep '^AWS_ACCESS_KEY_ID=' "$LOCAL_ENV" | cut -d'=' -f2)
    AWS_SECRET_ACCESS_KEY=$(grep '^AWS_SECRET_ACCESS_KEY=' "$LOCAL_ENV" | cut -d'=' -f2)
    AWS_TRANSFER_ACCELERATION=$(grep '^AWS_TRANSFER_ACCELERATION=' "$LOCAL_ENV" | cut -d'=' -f2 || echo "false")
    
    HAS_S3_CREDS=true
    if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
        HAS_S3_CREDS=false
        echo "⚠️  Local .env found but missing S3 credentials"
    fi
else
    echo "⚠️  No local .env found - S3 credentials will need manual setup"
    HAS_S3_CREDS=false
fi

# Create remote .env content
REMOTE_ENV_FILE="/tmp/mcp-server-remote.env"
cat > "$REMOTE_ENV_FILE" << EOF
# Figma MCP Server 2.0 - Production Configuration
# Auto-generated by deploy script on $(date)

NODE_ENV=production
PORT=3333

# AWS S3 Configuration (for image/screenshot uploads)
AWS_REGION=${AWS_REGION:-us-east-2}
AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-osmo-studio-public}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
AWS_TRANSFER_ACCELERATION=${AWS_TRANSFER_ACCELERATION:-false}
EOF

# Upload to EC2
echo ""
echo "Uploading to EC2..."
scp -i "$SSH_KEY" $SSH_OPTS "$PACKAGE_FILE" ubuntu@${PUBLIC_IP}:~/
scp -i "$SSH_KEY" $SSH_OPTS "$REMOTE_ENV_FILE" ubuntu@${PUBLIC_IP}:~/mcp-server-remote.env
echo "✓ Upload complete"

# Install on EC2
echo ""
echo "Installing on EC2..."
ssh -i "$SSH_KEY" $SSH_OPTS ubuntu@${PUBLIC_IP} << 'REMOTE_SCRIPT'
set -e

echo ""
echo ">> Updating system packages..."
sudo apt-get update -y -qq

echo ""
echo ">> Installing Node.js 20..."
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
fi
node --version

echo ""
echo ">> Installing pnpm..."
if ! command -v pnpm &> /dev/null; then
    sudo npm install -g pnpm
fi
pnpm --version

echo ""
echo ">> Extracting deployment package..."
mkdir -p ~/mcp-server
cd ~/mcp-server
tar -xzf ~/mcp-server-2.0.tar.gz
rm ~/mcp-server-2.0.tar.gz

echo ""
echo ">> Installing dependencies..."
pnpm install --prod

echo ""
echo ">> Applying .env configuration..."
mv ~/mcp-server-remote.env ~/mcp-server/.env
cat ~/mcp-server/.env | grep -v SECRET | grep -v KEY || true

echo ""
echo ">> Creating systemd service..."
sudo tee /etc/systemd/system/mcp-server.service > /dev/null << 'SERVICEFILE'
[Unit]
Description=Figma MCP Server 2.0
After=network.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/mcp-server
ExecStart=/usr/bin/node dist/bin.js --host 0.0.0.0
Restart=always
RestartSec=10
EnvironmentFile=/home/ubuntu/mcp-server/.env

[Install]
WantedBy=multi-user.target
SERVICEFILE

echo ""
echo ">> Starting service..."
sudo systemctl daemon-reload
sudo systemctl enable mcp-server
sudo systemctl restart mcp-server

echo ""
echo ">> Service status:"
sudo systemctl status mcp-server --no-pager || true
REMOTE_SCRIPT

# Cleanup temp files
rm -f "$REMOTE_ENV_FILE"

echo ""
echo "=========================================="
echo "  ✅ Deployment Complete!"
echo "=========================================="
echo ""
echo "Server URL: http://${PUBLIC_IP}:3333"
echo ""
if [ "$HAS_S3_CREDS" = true ]; then
    echo "✅ S3 credentials auto-injected from local .env"
    echo "   Bucket: ${AWS_BUCKET_NAME}"
    echo "   Region: ${AWS_REGION}"
else
    echo "⚠️  S3 credentials not configured."
    echo "   Run: ./4_setup_s3.sh ${PUBLIC_IP}"
fi
echo ""
echo "Server Management:"
echo "  Status:  ssh -i ${SSH_KEY} ubuntu@${PUBLIC_IP} 'sudo systemctl status mcp-server'"
echo "  Logs:    ssh -i ${SSH_KEY} ubuntu@${PUBLIC_IP} 'sudo journalctl -u mcp-server -f'"
echo "  Restart: ssh -i ${SSH_KEY} ubuntu@${PUBLIC_IP} 'sudo systemctl restart mcp-server'"
echo ""
