#!/bin/bash
# =============================================================================
# 4. Setup S3 Credentials
# =============================================================================
# Configures AWS S3 credentials on the EC2 instance for image uploads.
# Usage: ./4_setup_s3.sh <PUBLIC_IP>
# =============================================================================

set -e

if [ -z "$1" ]; then
    echo "Usage: ./4_setup_s3.sh <PUBLIC_IP>"
    echo ""
    echo "Example: ./4_setup_s3.sh 3.145.67.89"
    exit 1
fi

PUBLIC_IP=$1
KEY_NAME="mcp-server-key"
SSH_KEY="$HOME/.ssh/${KEY_NAME}.pem"
SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

echo ""
echo "=========================================="
echo "  Configure S3 Credentials"
echo "=========================================="
echo ""
echo "The MCP server needs S3 credentials to upload images and screenshots."
echo "Figma tokens are passed per-request (not stored on server)."
echo ""

# Check SSH key exists
if [ ! -f "$SSH_KEY" ]; then
    echo "❌ SSH key not found: ${SSH_KEY}"
    exit 1
fi

# Prompt for S3 credentials
read -p "AWS Region [us-east-2]: " AWS_REGION
AWS_REGION=${AWS_REGION:-us-east-2}

read -p "S3 Bucket Name [osmo-studio-public]: " AWS_BUCKET_NAME
AWS_BUCKET_NAME=${AWS_BUCKET_NAME:-osmo-studio-public}

read -p "AWS Access Key ID: " AWS_ACCESS_KEY_ID
if [ -z "$AWS_ACCESS_KEY_ID" ]; then
    echo "❌ AWS Access Key ID is required."
    exit 1
fi

read -sp "AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
echo ""
if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
    echo "❌ AWS Secret Access Key is required."
    exit 1
fi

read -p "Enable S3 Transfer Acceleration? [false]: " AWS_TRANSFER_ACCELERATION
AWS_TRANSFER_ACCELERATION=${AWS_TRANSFER_ACCELERATION:-false}

# Generate .env content
ENV_CONTENT="# Figma MCP Server 2.0 - Production Configuration
# Generated by 4_setup_s3.sh on $(date)

NODE_ENV=production
PORT=3333

# AWS S3 Configuration (for image/screenshot uploads)
AWS_REGION=${AWS_REGION}
AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_TRANSFER_ACCELERATION=${AWS_TRANSFER_ACCELERATION}
"

echo ""
echo "Uploading configuration to EC2..."

# Upload .env file
echo "$ENV_CONTENT" | ssh -i "$SSH_KEY" $SSH_OPTS ubuntu@${PUBLIC_IP} 'cat > ~/mcp-server/.env'
echo "✓ Configuration uploaded"

# Restart service
echo ""
echo "Restarting MCP server..."
ssh -i "$SSH_KEY" $SSH_OPTS ubuntu@${PUBLIC_IP} 'sudo systemctl restart mcp-server'
echo "✓ Service restarted"

# Wait and check status
sleep 2
echo ""
echo "Service status:"
ssh -i "$SSH_KEY" $SSH_OPTS ubuntu@${PUBLIC_IP} 'sudo systemctl status mcp-server --no-pager' || true

echo ""
echo "=========================================="
echo "  ✅ S3 Configuration Complete!"
echo "=========================================="
echo ""
echo "Server URL:    http://${PUBLIC_IP}:3333"
echo "S3 Bucket:     s3://${AWS_BUCKET_NAME}"
echo "Region:        ${AWS_REGION}"
echo ""
echo "The server can now:"
echo "  - Download and process Figma images"
echo "  - Upload images to S3 with permanent URLs"
echo "  - Take screenshots of Figma nodes"
echo ""
echo "To verify, check the logs:"
echo "  ssh -i ${SSH_KEY} ubuntu@${PUBLIC_IP} 'sudo journalctl -u mcp-server -f'"
echo ""
